### ISSUE TITLE
Update to support gcloud==0.12.1

### ISSUE THREAD

**Issue by erichiggins** [LeadPages/gcloud_requests#9]
`gcloud-python` [released a patch version (0.12.1) on Apr 19th](https://github.com/GoogleCloudPlatform/gcloud-python/releases). It'd be great if this library could be upgraded to support that version to include the bugfixes that it contains.

**Comment by bendemaree** [comment]
@erichiggins Thanks for the request! This has been updated; I will cut a release shortly. If you were using the Cloud Datastore client, note the emulator URL change...

**Comment by bendemaree** [comment]
[The release](https://pypi.python.org/pypi/gcloud-requests/0.10.0) is now available.

**Comment by erichiggins** [comment]
Awesome, thank you!
